package application;

public enum OpID {
	LOGIN,
	REGISTER,
	SEARCHMYSONGS,
	SEARCHMYPLAYLISTS,
	SEARCHCURRENTPLAYLIST,
	ADDPLAYLIST,
	DELETEPLAYLIST,
	ADDSONGTOPLAYLIST,
	DELETESONGFROMPLAYLIST,
	SEARCHALLSONGS;
}
