package application;

/**
 * Class to attach operations to enums.
 * @author Wesley
 *
 */
public enum OpID {
	LOGIN,
	REGISTER,
	SEARCHMYSONGS,
	SEARCHMYPLAYLISTS,
	SEARCHCURRENTPLAYLIST,
	ADDPLAYLIST,
	DELETEPLAYLIST,
	ADDSONGTOPLAYLIST,
	DELETESONGFROMPLAYLIST,
	SEARCHALLSONGS,
	GETNUMBEROFFRAGMENTS,
	GETSONGBYTES;
}
